import type { ClassEvent } from './types.ts';

export const mockEvents: ClassEvent[] = [
  // Week 1 - May 2026
  {
    id: '1',
    title: 'Mathematics',
    subject: 'Algebra & Calculus',
    startHour: 9,
    startMinute: 0,
    durationHours: 2,
    state: 'green',
    date: '2026-05-18',
  },
  {
    id: '2',
    title: 'Physics',
    subject: 'Mechanics',
    startHour: 14,
    startMinute: 0,
    durationHours: 1.5,
    state: 'green',
    date: '2026-05-19',
  },
  {
    id: '3',
    title: 'Chemistry',
    subject: 'Organic Chemistry',
    startHour: 10,
    startMinute: 30,
    durationHours: 1,
    state: 'yellow',
    date: '2026-05-20',
  },
  {
    id: '4',
    title: 'English',
    subject: 'Literature',
    startHour: 16,
    startMinute: 0,
    durationHours: 1,
    state: 'red',
    date: '2026-05-21',
  },
  {
    id: '5',
    title: 'Biology',
    subject: 'Genetics',
    startHour: 11,
    startMinute: 0,
    durationHours: 2,
    state: 'green',
    date: '2026-05-22',
  },
  {
    id: '6',
    title: 'History',
    subject: 'World History',
    startHour: 13,
    startMinute: 30,
    durationHours: 1,
    state: 'yellow',
    date: '2026-05-23',
  },
  // Week 2
  {
    id: '7',
    title: 'Mathematics',
    subject: 'Geometry',
    startHour: 9,
    startMinute: 0,
    durationHours: 2,
    state: 'green',
    date: '2026-05-25',
  },
  {
    id: '8',
    title: 'Physics',
    subject: 'Thermodynamics',
    startHour: 15,
    startMinute: 0,
    durationHours: 1.5,
    state: 'green',
    date: '2026-05-26',
  },
  {
    id: '9',
    title: 'Computer Science',
    subject: 'Programming',
    startHour: 18,
    startMinute: 0,
    durationHours: 2,
    state: 'yellow',
    date: '2026-05-27',
  },
  {
    id: '10',
    title: 'English',
    subject: 'Essay Writing',
    startHour: 10,
    startMinute: 0,
    durationHours: 1,
    state: 'green',
    date: '2026-05-28',
  },
  {
    id: '11',
    title: 'Biology',
    subject: 'Cell Biology',
    startHour: 14,
    startMinute: 30,
    durationHours: 1.5,
    state: 'red',
    date: '2026-05-29',
  },
  // Additional May dates
  {
    id: '12',
    title: 'Art',
    subject: 'Painting',
    startHour: 13,
    startMinute: 0,
    durationHours: 2,
    state: 'green',
    date: '2026-05-30',
  },
  // June events
  {
    id: '13',
    title: 'Mathematics',
    subject: 'Statistics',
    startHour: 9,
    startMinute: 30,
    durationHours: 1.5,
    state: 'green',
    date: '2026-06-02',
  },
  {
    id: '14',
    title: 'Chemistry',
    subject: 'Lab Work',
    startHour: 11,
    startMinute: 0,
    durationHours: 2,
    state: 'yellow',
    date: '2026-06-05',
  },
  {
    id: '15',
    title: 'Physics',
    subject: 'Electromagnetism',
    startHour: 16,
    startMinute: 30,
    durationHours: 1,
    state: 'green',
    date: '2026-06-09',
  },
  {
    id: '16',
    title: 'Music',
    subject: 'Piano',
    startHour: 19,
    startMinute: 0,
    durationHours: 1,
    state: 'yellow',
    date: '2026-06-12',
  },
  // July events
  {
    id: '17',
    title: 'Mathematics',
    subject: 'Advanced Calculus',
    startHour: 10,
    startMinute: 0,
    durationHours: 2,
    state: 'green',
    date: '2026-07-08',
  },
  {
    id: '18',
    title: 'Geography',
    subject: 'Climate Studies',
    startHour: 14,
    startMinute: 0,
    durationHours: 1,
    state: 'red',
    date: '2026-07-15',
  },
];
